# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET # name of git action we selected, continous integration .NET

# Below are like stages 
on: #when you push to this master branch, set jobs e.g build 
  push:
    branches: [ "master" ] # specifying the branch pushing to
  pull_request:
    branches: [ "master" ] # this is not necessary

jobs: #setting the jobs, actions to be performed
  build: # the first job is build the project

    runs-on: ubuntu-latest

    steps: # below are defualt git hub actions settings. they inbuilt command
    - uses: actions/checkout@v4 # stating the tool we are using (git hub actions)
    - name: Setup .NET # name of git action we selected, continous integration .NET
      uses: actions/setup-dotnet@v4 # setting up dotnet environment
      with:
        dotnet-version: 8.0.x # dotnet version of our project
    - name: Restore dependencies # next action
      run: dotnet restore # this is the restore command
    - name: Build #next action
      run: dotnet build --no-restore # this is the build command
    - name: Test # the next action is test, we add it if there is test in the project. test drivenprojet
      run: dotnet test --no-build --verbosity normal # test command


